export const projects = [
  {
    title: 'The Art Station',
    image: '/project-images/art station.png',
    description: 'A modern full-stack e-commerce platform for art lovers to explore and purchase artwork. Built using Next.js with dynamic product pages and cart functionality.',
    link: 'https://milestone-3-e-commerce-website-1oz5.vercel.app/',
    github: 'https://github.com/munazhairfan/milestone-3-E-commerce-website',
    category: 'E-Commerce',
  },
  {
    title: 'Regal House',
    image: '/project-images/rh.png',
    description: 'An elegant online furniture store with seamless browsing and checkout experience. Developed using Next.js and Tailwind CSS.',
    link: 'https://regal-house-o15z.vercel.app/',
    github: 'https://github.com/munazhairfan/Regal-House',
    category: 'E-Commerce',
  },
  {
    title: 'Whisk & Wonder',
    image: '/project-images/ww.png',
    description: 'A blog-style website dedicated to baking recipes and culinary stories. Built with Next.js and optimized for content sharing.',
    link: 'https://mileestone-3-blogs.vercel.app/',
    github: 'https://github.com/munazhairfan/milestone-3-BLOGS',
    category: 'Creative & Design',
  },
  {
    title: 'Unit Converter',
    image: '/project-images/unit-converter.png',
    description: 'A Streamlit-powered app for converting between various units of measurement like length, weight, and temperature in a clean interface.',
    link: 'https://munazhairfan-unit-converter-main-jeiajf.streamlit.app/',
    github: 'https://github.com/munazhairfan/unit-converter',
    category: 'Tools & Utilities',
  },
  {
    title: 'Password Strength Meter',
    image: '/project-images/pw-meter.png',
    description: 'A secure password checker that rates strength based on common patterns, length, and entropy. Built with Streamlit and Python.',
    link: 'https://password-strength-meter-gjemyvv7csbvoancjypgh5.streamlit.app/',
    github: 'https://github.com/munazhairfan/password-strength-meter',
    category: 'Tools & Utilities',
  },
  {
    title: 'Lockbox',
    image: '/project-images/lockbox.png',
    description: 'A data encryption app that lets users store secrets with secure passkey protection using Fernet and PBKDF2 hashing.',
    link: 'https://lockbox.streamlit.app/',
    github: 'https://github.com/munazhairfan/LockBox',
    category: 'Tools & Utilities',
  },
  {
    title: 'Peppy',
    image: '/project-images/peppy.png',
    description: 'A friendly AI chatbot powered by Hugging Face models and Streamlit. Supports natural conversation and sentiment-aware responses.',
    link: 'https://chatbot-kqgnxzplgv4extr9rurqb7.streamlit.app/',
    github: 'https://github.com/munazhairfan/chatbot',
    category: 'AI & Chatbots',
  },
  {
    title: 'Canvas',
    image: '/project-images/canvas.png',
    description: 'A collaborative drawing board built with Streamlit, where users can sketch ideas in real-time on a blank canvas.',
    link: 'https://munazhairfan-canvas-canvas-y0gkpl.streamlit.app/',
    github: 'https://github.com/munazhairfan/Canvas',
    category: 'Creative & Design',
  },
  {
    title: 'Doctor',
    image: '/project-images/doctor.png',
    description: "A BMI calculator and health advisor that suggests lifestyle tips based on the user's BMI, age, and weight using Streamlit.",
    link: 'https://munazhairfan-bmi-calculator-main-vyxghv.streamlit.app/',
    github: 'https://github.com/munazhairfan/BMI-Calculator',
    category: 'Health & Lifestyle',
  },
];
